"""
MetaCheck Data Models

All Pydantic models used throughout the MetaCheck system.
"""

from datetime import datetime
from typing import List, Optional, Literal, Dict
from pydantic import BaseModel, Field


# ============================================================================
# CORE DATA MODELS
# ============================================================================

class Claim(BaseModel):
    """A single factual claim extracted from text"""
    text: str
    worthiness_score: float = Field(
        ge=0.0,
        le=1.0,
        default=0.8,
        description=(
            "Priority score (0.0-1.0) for verification based on: "
            "1) SPECIFICITY: concrete facts/numbers/dates > vague statements; "
            "2) VERIFIABILITY: requires external sources > common knowledge; "
            "3) IMPACT: potential harm if false > low-stakes information. "
            "Scoring guide: "
            "0.8-1.0 = High priority (specific statistics, recent events, controversial claims, health/safety info); "
            "0.5-0.7 = Medium priority (verifiable but lower stakes, historical facts, attributable quotes); "
            "0.0-0.4 = Low priority (well-known facts, definitions, subjective opinions, trivial details). "
            "Consider: Would this claim mislead readers if unchecked? Does it contain checkable details?"
        ),
    )

    extracted_at: datetime = Field(default_factory=datetime.now)


class ClaimList(BaseModel):
    """List of extracted claims"""
    claims: List[Claim]
    extraction_method: str = "AI claim extractor"


class Evidence(BaseModel):
    """A single piece of evidence from a source"""
    source_name: str
    source_type: Literal["fact_check", "wikipedia", "web_search"]
    url: str
    snippet: str
    relevance_score: float = Field(ge=0.0, le=1.0, default=0.7)
    credibility_score: float = Field(ge=0.0, le=1.0, default=0.7)
    stance: Optional[Literal["supports", "refutes", "neutral", "unclear"]] = None


class MetacognitiveStep(BaseModel):
    """A step in the metacognitive reasoning process"""
    timestamp: datetime = Field(default_factory=datetime.now)
    agent: str
    action: str
    reasoning: str
    confidence: Optional[float] = None


# ============================================================================
# SEARCH STATUS MODELS
# ============================================================================

class SearchStatus(BaseModel):
    """Status of a search operation - tracks success, failure, or no results"""
    tool: Literal["web_search", "wikipedia", "google_fact_check"]
    status: Literal["success", "error", "no_api_key", "no_results"]
    results_count: int = 0
    error_message: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)


class SearchStatusSummary(BaseModel):
    """Summary of all search statuses for a verification"""
    web_search: Optional[SearchStatus] = None
    wikipedia: Optional[SearchStatus] = None
    google_fact_check: Optional[SearchStatus] = None

    @property
    def any_failures(self) -> bool:
        """Check if any search failed"""
        statuses = [self.web_search, self.wikipedia, self.google_fact_check]
        return any(s and s.status in ("error", "no_api_key") for s in statuses)

    @property
    def failed_searches(self) -> List[str]:
        """Get list of failed search tools"""
        failed = []
        for name, status in [
            ("web_search", self.web_search),
            ("wikipedia", self.wikipedia),
            ("google_fact_check", self.google_fact_check)
        ]:
            if status and status.status in ("error", "no_api_key"):
                failed.append(name)
        return failed


class EvidenceBundle(BaseModel):
    """Structured evidence payload returned by tools"""
    evidence: List[Evidence]
    search_status: Optional[SearchStatusSummary] = None


# ============================================================================
# ASSESSMENT MODELS
# ============================================================================

class ContradictionDetection(BaseModel):
    """Detection of contradictory evidence"""
    detected: bool = False
    contradicting_sources: List[str] = []
    description: str = ""
    severity: Literal["minor", "moderate", "major"] = "minor"


# ============================================================================
# EDUCATIONAL TRANSPARENCY MODELS
# ============================================================================

class SearchQuery(BaseModel):
    """Record of search queries generated by the AI for educational transparency"""
    query_text: str
    query_reasoning: str  # WHY this query was generated
    search_strategy: Literal["direct", "broad", "contextual", "fact_check"]
    source_tool: Literal["WebSearchTool", "wikipedia_search_tool", "google_fact_check_tool"]
    timestamp: datetime = Field(default_factory=datetime.now)
    results_count: int = 0
    results_used: int = 0  # How many results were actually assessed


class DomainClassification(BaseModel):
    """Domain-based credibility classification result"""
    credibility_score: float = Field(ge=0.0, le=1.0)
    category: str  # e.g., "government_public", "scientific_journals", "general_web"
    description: str
    reasoning: str
    justification: str
    limitations: str


class SourceAssessment(BaseModel):
    """Detailed assessment of a single source for educational transparency"""
    source_name: str
    source_type: Literal["fact_check", "wikipedia", "web_search"]
    url: str
    title: str = ""

    # Domain classification (only for web_search)
    domain_category: Optional[str] = None  # e.g., "government_public", "scientific_journals"
    domain_classification: Optional[DomainClassification] = None  # Full classification result

    # Relevance
    relevance_score: float = Field(ge=0.0, le=1.0)
    relevance_reasoning: str  # WHY this relevance score?
    relevance_factors: List[str] = []  # ["directly addresses claim", "contains key terms"]

    # Stance
    stance: Literal["supports", "refutes", "neutral", "unclear"]
    stance_reasoning: str  # WHY this stance?
    key_quotes: List[str] = []  # Quotes that influenced stance determination

    # Credibility
    credibility_score: float = Field(ge=0.0, le=1.0)
    credibility_reasoning: str  # HOW was this score determined?
    credibility_factors: List[str] = []  # ["professional fact-checker", "recent publication"]

    # Content
    snippet: str
    full_text_available: bool = False
    publication_date: Optional[str] = None
    author: Optional[str] = None


class VerdictReasoning(BaseModel):
    """Detailed reasoning for verdict decision - educational transparency"""
    final_verdict: Literal["SUPPORTED", "REFUTED", "INSUFFICIENT_INFORMATION", "CONFLICTING_EVIDENCE"]
    confidence: float = Field(ge=0.0, le=1.0)

    # Evidence weighting calculation
    supporting_sources_count: int
    supporting_weight: float  # Sum of credibility scores
    supporting_key_sources: List[str] = []  # Names of key supporting sources

    refuting_sources_count: int
    refuting_weight: float  # Sum of credibility scores
    refuting_key_sources: List[str] = []  # Names of key refuting sources

    neutral_sources_count: int
    neutral_weight: float

    unclear_sources_count: int

    # Decision logic
    primary_reason: str  # Main reason for this verdict
    decision_rule_applied: str  # Which rule from VERDICT_CRITERIA was applied

    # Alternatives considered
    alternative_verdicts_considered: List[str] = []  # e.g., ["CONFLICTING_EVIDENCE", "INSUFFICIENT_INFORMATION"]
    why_not_alternatives: str = ""  # Why alternatives were rejected

    # Decisive factors
    decisive_sources: List[str] = []  # Which sources tipped the decision
    decisive_factor: str  # What ultimately determined the verdict

    # Confidence calculation
    confidence_reasoning: str  # Why this confidence level
    confidence_factors: List[str] = []  # ["high source credibility", "unanimous agreement"]


class RejectedSource(BaseModel):
    """A source that was found but rejected from analysis"""
    url: str
    reason: str


class MetacognitiveDetail(BaseModel):
    """Complete metacognitive record for one claim - full educational transparency"""
    claim: str

    # Phase 1: Query Generation
    search_queries: List[SearchQuery] = []
    search_strategy_summary: str = ""

    # Phase 2: Evidence Collection
    sources_found: int = 0
    sources_assessed: List[SourceAssessment] = []
    sources_rejected: List[RejectedSource] = []  # Sources found but not used, with reasons

    # Phase 3: Evidence Analysis
    contradiction_detection: Optional[ContradictionDetection] = None
    verdict_reasoning: Optional[VerdictReasoning] = None

    # Phase 4: Meta-analysis
    # Phase 5: Limitations & Uncertainties
    ai_uncertainties: List[str] = []  # What the AI couldn't determine
    assumptions_made: List[str] = []  # Assumptions in the assessment
    potential_weaknesses: List[str] = []  # Where this assessment might be wrong

    # Overall
    total_assessment_time: Optional[float] = None  # Seconds
    metacognitive_summary: str = ""  # High-level summary for students


# ============================================================================
# VERIFICATION RESULT MODELS
# ============================================================================

class VerificationResult(BaseModel):
    """Result of verifying a single claim - Enhanced with full metacognitive detail"""
    claim: str
    verdict: Literal["SUPPORTED", "REFUTED", "INSUFFICIENT_INFORMATION", "CONFLICTING_EVIDENCE"]
    confidence: float = Field(ge=0.0, le=1.0)
    justification: str
    key_sources: List[str]  # Format: "Source Name [URL]"
    evidence_list: List[Evidence] = []
    metacognitive_steps: List[MetacognitiveStep] = []

    # Enhanced metacognitive details for educational transparency
    metacognitive_detail: Optional[MetacognitiveDetail] = None


class FinalAssessment(BaseModel):
    """Final assessment of all claims"""
    input_text: str
    total_claims: int
    claim_results: List[VerificationResult]
    overall_credibility: str
    mode: Literal["basic", "comprehensive"] = "basic"
    generated_at: datetime = Field(default_factory=datetime.now)

    # Search status tracking - shows which searches succeeded/failed
    search_status: Optional[SearchStatusSummary] = None


class OrchestratorOutput(BaseModel):
    """Structured output from the orchestrator with all verified claims"""
    claim_results: List[VerificationResult]
    summary: str = ""


class ComparisonAnalysis(BaseModel):
    """Analysis comparing student claims with AI-extracted claims"""
    overall_summary: str  # High-level summary of agreement/disagreement
    strengths: List[str]  # What the student did well
    areas_for_improvement: List[str]  # What could be improved
    key_insights: List[str]  # Important insights from the comparison
    claim_by_claim_feedback: List[str]  # Detailed feedback for each claim pair
    learning_opportunities: List[str]  # Specific learning suggestions
    encouragement: str  # Positive, encouraging closing message


# Rebuild models with forward references
VerificationResult.model_rebuild()
